// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFiQdjL0FwFo7G9OTezDCpcwQp9fcHCHs',
    appId: '1:173610014202:web:59deb41d59dc1cbbd34043',
    messagingSenderId: '173610014202',
    projectId: 'fruits-hub-13a82',
    authDomain: 'fruits-hub-13a82.firebaseapp.com',
    storageBucket: 'fruits-hub-13a82.firebasestorage.app',
    measurementId: 'G-B8PGYP6DK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPT9PrQWwxGPXeV26XrwTeyZrarWDz4g',
    appId: '1:173610014202:android:a39e353185668cded34043',
    messagingSenderId: '173610014202',
    projectId: 'fruits-hub-13a82',
    storageBucket: 'fruits-hub-13a82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2_hUJGLdFtnLXjUqmu2jlkc0UXxPdNdQ',
    appId: '1:173610014202:ios:8e13612b33efd49cd34043',
    messagingSenderId: '173610014202',
    projectId: 'fruits-hub-13a82',
    storageBucket: 'fruits-hub-13a82.firebasestorage.app',
    androidClientId: '173610014202-5g92ls1ufak5boliia7p43omobnqa6c5.apps.googleusercontent.com',
    iosClientId: '173610014202-81rfuvf8qjvrikndlqmdnghlgjdvuik0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2_hUJGLdFtnLXjUqmu2jlkc0UXxPdNdQ',
    appId: '1:173610014202:ios:8e13612b33efd49cd34043',
    messagingSenderId: '173610014202',
    projectId: 'fruits-hub-13a82',
    storageBucket: 'fruits-hub-13a82.firebasestorage.app',
    androidClientId: '173610014202-5g92ls1ufak5boliia7p43omobnqa6c5.apps.googleusercontent.com',
    iosClientId: '173610014202-81rfuvf8qjvrikndlqmdnghlgjdvuik0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFiQdjL0FwFo7G9OTezDCpcwQp9fcHCHs',
    appId: '1:173610014202:web:a9e7196e293ac3a2d34043',
    messagingSenderId: '173610014202',
    projectId: 'fruits-hub-13a82',
    authDomain: 'fruits-hub-13a82.firebaseapp.com',
    storageBucket: 'fruits-hub-13a82.firebasestorage.app',
    measurementId: 'G-FQXCYTB3CX',
  );
}
